# wallust Yazi theme template
# Place as ~/.config/wallust/templates/yazi-theme.toml or similar
# and run: wallust template ~/.config/wallust/templates/yazi-theme.toml

[manager]
cwd = { fg = "#484B54" }

preview_hints   = { fg = "#60637F" }

hovered         = { fg = "#10100F", bg = "#737696" }
preview_hovered = { fg = "#10100F", bg = "#737696" }

find_keyword  = { fg = "#60637F", bold = true, italic = true }
find_position = { fg = "#8488A8" }

marker_copied   = { fg = "#555A6B", bg = "#555A6B" }
marker_cut      = { fg = "#484B54",  bg = "#484B54" }
marker_selected = { fg = "#737696", bg = "#737696" }

count_copied   = { fg = "#10100F", bg = "#555A6B" }
count_cut      = { fg = "#10100F", bg = "#484B54" }
count_selected = { fg = "#10100F", bg = "#737696" }

border_symbol = "│"
border_style  = { fg = "#85878D" }

tab_active   = { fg = "#10100F", bg = "#BEC1CA" }
tab_inactive = { fg = "#D7D9E0", bg = "#383838" }
tab_width    = 2

[status]
bg = "#383838"
separator_open  = "█"
separator_close = "█"
separator_style = { fg = "#383838", bg = "#85878D" }

mode_normal = { fg = "#737696", bold = true }
mode_select = { fg = "#555A6B",  bold = true }
mode_unset  = { fg = "#484B54",  bold = true }

progress_label = { fg = "#D7D9E0", bold = true }
progress_normal = { fg = "#737696" }
progress_error  = { fg = "#484B54" }

[select]
border   = { fg = "#737696" }
active   = { fg = "#8488A8", bold = true }
inactive = {}

[input]
border   = { fg = "#737696" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border = { fg = "#85878D" }


[tasks]
border  = { fg = "#737696" }
title   = {}
hovered = { underline = true }

[help]
on      = { fg = "#8488A8" }
run     = { fg = "#8E93A6" }
desc    = { fg = "#BEC1CA" }
hovered = { bg = "#85878D", bold = true }
footer  = { fg = "#484B54", bg = "#383838" }

[filetype]
rules = [
  { mime = "image/*", fg = "#8E93A6" },
  { mime = "video/*", fg = "#8E93A6" },
  { mime = "audio/*", fg = "#8E93A6" },
  { mime = "application/*zip", fg = "#8488A8" },
  { mime = "application/x-{tar,bzip*,gzip,7z-compressed,xz,rar}", fg = "#8488A8" },
  { name = "*", fg = "#D7D9E0" },
  { name = "*/", fg = "#737696" },
]
